# Generated by Django 3.1 on 2020-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_item_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_details',
            name='first_added',
        ),
        migrations.RemoveField(
            model_name='item_details',
            name='last_update',
        ),
        migrations.AddField(
            model_name='item_details',
            name='area',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='item_details',
            name='location_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='item_details',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='item_details',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='item_details',
            name='type',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='item_details',
            name='year',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
