# Generated by Django 3.1 on 2020-08-31 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200831_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraper.item'),
        ),
    ]
