# Generated by Django 3.1 on 2020-08-31 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200831_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.item'),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='area',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='location_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='rooms',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item_details',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
