# Generated by Django 3.1 on 2020-08-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20200831_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
