# Generated by Django 3.1 on 2020-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_item_details_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='zip',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
