# Generated by Django 3.1 on 2020-09-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_item_details_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_details',
            old_name='location_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='item_details',
            old_name='type',
            new_name='obj_cat',
        ),
        migrations.AddField(
            model_name='item_details',
            name='balcony',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='fed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='first_occupancy',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='garden',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='kitchen',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='pic',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item_details',
            name='sales_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
