# Generated by Django 3.1 on 2020-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20200904_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='first_occupancy',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
