# Generated by Django 3.1 on 2020-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20200904_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_details',
            name='area_effective',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
