# Generated by Django 3.1 on 2020-09-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_item_details_area_effective'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_details',
            old_name='area_effective',
            new_name='areaeffective',
        ),
    ]
