# Generated by Django 3.1 on 2020-09-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_auto_20200906_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_details',
            old_name='sales_type',
            new_name='marketingtype',
        ),
    ]
